import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local';

const Montserrat = localFont({ src: '../public/fonts/Montserrat-VariableFont_wght.ttf' });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={Montserrat.className}
      >
        {children}
      </body>
    </html>
  );
}
